# Site settings
title: 2Sherpas Blog
email: 2SherpasTeam@gmail.com.com
description: Our space to express how we see the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-info']
  Contact : ['Contact', '/contact', 'fa-send']
  David : ['David', '/author/david', 'fa-user']
  Jaime : ['Jaime', '/author/jaime', 'fa-laptop']
single_footer: '<p>Our space to express how we see the world <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Writer: ['2Sherpas', '/about']


# Build settings
# markdown: kramdown
